@startuml questions

class questions{
  ====
  + 作为使用者, 当我们看到`const`成员函数后, 应该想到什么呢?
  ====
  + 对于一般的`getter`, `setter`, 通常情况下, 谁会使用`const` 成员函数, 谁不会使用呢? 为什么呢?
  + 如果某个`getter`返回了属性的引用, 这样再强调该成员函数为`const`成员函数是否合理呢? 为什么呢? 如果不合理, 怎么改变才合理呢? (看不懂下面提供了参考代码)
  `class A{
  private:
      int x;
  public:
      int& getX() const {return x;}
  };`
  ====
  + 在问题`3`中, 我们针对的是返回类属性. 如果我们返回的是当前类对象(`*this`), 那么`double const`或许会更有意义, 请分析一下. (参考代码如下)
  `const complex& func() const{return *this;}`
  ====
  + 在问题`4`中, 我们只是单纯地分析了`double const` 情况, 那么请对如下各种情况分析下.
  `complex& func() const {return *this;}
  const complex& func() {return *this;}
  complex& func() {return *this;}`
  ====
  + 当我们看到非`const`成员函数时, 应该考虑什么呢?
}

@enduml












