@startuml main
skinparam DefaultTextAlignment center
title 记忆层面策略活动图

rectangle 主要记忆图_Part1{
    start
    :Anki复习\n(什么时候复习?);
    if (是否记住?) then (是)
    :正常间隔复习;
    else (否 / 遗忘)
    :去 GitHub 查 Mapping;
    :查找 GitHub 仓库\n(知识 \ 理解 \ 错题 \ 题目);
    :回顾知识内容\n(具体怎么回顾?);
    :重新理解\n(具体怎么理解?);
    :更新 / 新增 Anki 卡片;
    endif

    :回到复习;

    stop
}
@enduml