@startuml 00questions
class 00questions{
  ====
  + 如下形式的实例化, 其内部可能得构造函数形式有哪些?
  `int main(){
    complex c1;
    }`
  ====
  + 是否存在使得这种`complex c1;`实例化方式失败的方法?
  ====
  + 下列实例化对象方式是否正确? 存在的问题是什么? 那么正确调用方式是什么? `complex c1();`
  ====
  + 参数数量不对等的函数重载, 是否一定可以执行?
  ====
  + 使用含有默认值构造函数时, 是不是尽量避免重载? 或者说, 重载时是不是尽量避免使用默认值参数?
}

@enduml












